version: '3'

services:
  database:
    image: postgres:14.1
    restart: always
    container_name: bidnamic-database
    environment:
      POSTGRES_USER: &db_user bidnamicuser # TO DO: USE _FILE NOTATION
      POSTGRES_PASSWORD: &db_password bidnamicpassword
      POSTGRES_DB: &db_name bidnamic
    ports:
      - "55432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  endpoint:
    build:
      context: .
      dockerfile: Dockerfile.endpoint
    container_name: bidnamic-endpoint
    command: endpoint
    depends_on:
      - database
    ports:
      - "8090:8000"
    volumes:
      - .:/endpoint
    environment:
      DATABASE_NAME: *db_name
      DATABASE_PASSWORD: *db_password
      DATABASE_USER: *db_user
      DATABASE_HOST: database
      DATABASE_PORT: 5432

  loader:
    build:
      context: .
      dockerfile: Dockerfile.loader
    container_name: bidnamic-loader
    command: loader
    depends_on:
      - database
    environment:
      DATABASE_NAME: *db_name
      DATABASE_PASSWORD: *db_password
      DATABASE_USER: *db_user
      DATABASE_HOST: database
      DATABASE_PORT: 5432
