version: '3'

services:
  database:
    image: postgres:14.1
    restart: always
    container_name: bidnamic-database
    environment:
      POSTGRES_USER: bidnamicuser # TO DO: USE _FILE NOTATION
      POSTGRES_PASSWORD: bidnamicpassword
      POSTGRES_DB: bidnamic
    ports:
      - "55432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
