# use official python3.9 base image
FROM python:3.9

# expose port for python application to listen on the container
EXPOSE 8000

# create working directory files and add files
WORKDIR /endpoint
COPY . .
RUN pwd && ls


# install python requirements
RUN pip install -r requirements.txt


ENTRYPOINT ["/endpoint/entrypoint.sh"]
